version: '2'
services:
  registry:
    image: demoregistry.dataman-inc.com/library/centos7-docker-registry:v2.5.0.2016090301
    restart: always
    volumes:
      - /data/registry:/storage
      - ./conf.d/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
  #mysql:
  #  image: deploy_mysql
  #  restart: always
  #  volumes:
  #    - /data/database:/var/lib/mysql
  #  env_file:
  #    - ./conf.d/db/env
  ui:
    image: demoregistry.dataman-inc.com/library/centos7-docker-harbor:v0.3.5.2016090300 
    env_file:
      - ./conf.d/ui/env
    restart: always
    volumes:
      - ./conf.d/ui/app.conf:/etc/ui/app.conf
      - ./conf.d/ui/private_key.pem:/etc/ui/private_key.pem
    depends_on:
      - mysql
      - registry
  jobservice:
    image: demoregistry.dataman-inc.com/library/centos7-docker-harborjobservice:v0.3.5.2016090300 
    env_file:
      - ./conf.d/jobservice/env
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs
      - ./conf.d/jobservice/app.conf:/etc/jobservice/app.conf
    depends_on:
      - ui
  proxy:
    image: demoregistry.dataman-inc.com/library/centos7-nginx-1.10.1:latest 
    restart: always
    volumes:
      - ./conf.d/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - registry
      - ui
